// <auto-generated />
using System;
using Africuisine.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Africuisine.Infrastructure.Migrations.AfricuisineDb
{
    [DbContext(typeof(AfricuisineDbContext))]
    partial class AfricuisineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Africuisine.Domain.Entities.Ingredients.IngredientCategory", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("LUserUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SeqNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_IngredientCategories_Name");

                    b.ToTable("IngredientCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b2581820-0243-4987-b21b-b217c143cb13",
                            Creation = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(1590),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(1605),
                            Name = "Proteins",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "3d4ce4a6-7003-4fd6-8eee-377a287089eb",
                            Creation = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(1691),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(1691),
                            Name = "Vegetables And Herbs",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "c33956a0-edb7-4f83-b49d-2f7da25ffc8b",
                            Creation = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(1706),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(1706),
                            Name = "Fruits",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "c1e22c83-0b67-4fc8-9414-f2984ab1d403",
                            Creation = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(1742),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(1743),
                            Name = "Grains And Starches",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "43b2d3fe-2152-4364-b0f0-1ad2111c0642",
                            Creation = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(1764),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(1765),
                            Name = "Dairy And Dairy Alternatives",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "fc2e0160-b821-4664-b0fa-4124b27b48e0",
                            Creation = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(1796),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(1797),
                            Name = "Condiments And Sauces",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "a9496a88-f51a-4e37-a852-f9b3ba4153a4",
                            Creation = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(1820),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(1820),
                            Name = "Spices And Seasonings",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "bf55451b-d8f0-4bc1-ac41-e435123d594f",
                            Creation = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(1839),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(1839),
                            Name = "Baking Ingredients",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "a9cddb7f-e576-4cb3-b58b-1198477c61f4",
                            Creation = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(1856),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(1857),
                            Name = "Nuts And Seeds",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "59d23a1d-2316-48f9-b9da-4f48aea2fb98",
                            Creation = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(1866),
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(1867),
                            Name = "Beverages",
                            SeqNo = 0
                        });
                });

            modelBuilder.Entity("Africuisine.Domain.Entities.Ingredients.Measurement", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LUserUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SeqNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Measurements_Name");

                    b.ToTable("Measurements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "aca690b8-d77f-4b37-9451-761e7ff05c73",
                            Abbreviation = "ml",
                            Creation = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(2843),
                            Description = "Used for liquids, such as water, milk, and oil",
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(2846),
                            Name = "Milliliter",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "32bdd405-38ce-4a3e-adfd-d5b7a53234c1",
                            Abbreviation = "l",
                            Creation = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(2854),
                            Description = "Larger volume measurements, often used for bulk liquids.",
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(2855),
                            Name = "Liters",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "19411061-3a4b-4801-818d-da1fe45e0324",
                            Abbreviation = "g",
                            Creation = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(2913),
                            Description = "Common unit for measuring dry ingredients like flour, sugar, and spices.",
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(2913),
                            Name = "Grams",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "eb313148-80a6-4bce-96fd-45bd735c2461",
                            Abbreviation = "kg",
                            Creation = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(2925),
                            Description = "Larger mass measurements, especially for bulk ingredients.",
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(2926),
                            Name = "Kilograms",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "011749af-1b84-4973-aa92-00e2d948dbc6",
                            Abbreviation = "tsp.",
                            Creation = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(2930),
                            Description = "Approximately 5 ml.",
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(2931),
                            Name = "Teaspoon",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "cd1fc083-72a2-4dd1-bf66-cba7307adbdd",
                            Abbreviation = "Tbsp",
                            Creation = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(2938),
                            Description = "Approximately 15 ml.",
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(2939),
                            Name = "Tablespoon",
                            SeqNo = 0
                        },
                        new
                        {
                            Id = "68e5711f-ce4d-423f-b460-606b16329ccc",
                            Abbreviation = "250 ml",
                            Creation = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(2944),
                            Description = "Used for both liquid and dry ingredients.",
                            LUserUpdate = "",
                            LastUpdate = new DateTime(2024, 4, 13, 19, 11, 26, 846, DateTimeKind.Local).AddTicks(2944),
                            Name = "Cup",
                            SeqNo = 0
                        });
                });

            modelBuilder.Entity("Africuisine.Domain.Entities.Recipes.RecipeCategory", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("LUserUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeqNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RecipeCategories");
                });

            modelBuilder.Entity("Africuisine.Domain.RecipePicture", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LUserUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeqNo")
                        .HasColumnType("int");

                    b.Property<string>("Uri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RecipePictures");
                });
#pragma warning restore 612, 618
        }
    }
}
